/* eslint-disable no-console */
/**
 * Generates typed ABIs and address maps from the compiled contracts and the
 * deployment records.
 *
 * Running this is the only supported way to get an ABI into the client or the
 * indexer. Hand copying one is how a client ends up calling a function signature
 * that no longer exists on chain.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..", "..", "..");
const CONTRACTS = path.join(ROOT, "packages", "contracts");
const ARTIFACTS = path.join(CONTRACTS, "artifacts", "contracts");
const DEPLOYMENTS = path.join(CONTRACTS, "deployments");
const OUT = path.join(__dirname, "..", "src", "generated");

/** Contract name to its source path under contracts/. */
const CONTRACT_FILES = {
  HesoyamToken: "token/HesoyamToken.sol",
  Flower: "token/Flower.sol",
  StrainCard: "token/StrainCard.sol",
  GrowBench: "token/GrowBench.sol",
  Plot: "token/Plot.sol",
  RevenueRouter: "core/RevenueRouter.sol",
  RandomBeacon: "core/RandomBeacon.sol",
  StakingVault: "core/StakingVault.sol",
  StrainRegistry: "game/StrainRegistry.sol",
  GrowGame: "game/GrowGame.sol",
  CardCrafter: "game/CardCrafter.sol",
  Marketplace: "market/Marketplace.sol",
  Dispensary: "market/Dispensary.sol",
  MockUSDC: "mocks/Mocks.sol",
  MockSwapAdapter: "mocks/Mocks.sol",
  // Testnet only. Absent from a mainnet deployments file, so every reader of
  // DEPLOYMENTS has to treat this address as optional already.
  Faucet: "testnet/Faucet.sol",
};

/** Deployment record key for each contract, where one exists. */
const DEPLOYMENT_KEYS = {
  HesoyamToken: "hesoyam",
  Flower: "flower",
  StrainCard: "strainCard",
  GrowBench: "bench",
  Plot: "plot",
  RevenueRouter: "router",
  RandomBeacon: "beacon",
  StakingVault: "vault",
  StrainRegistry: "strains",
  GrowGame: "game",
  CardCrafter: "crafter",
  Marketplace: "marketplace",
  Dispensary: "dispensary",
  MockUSDC: "settlement",
  Faucet: "faucet",
};

function lowerFirst(s) {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

function readAbi(name) {
  const rel = CONTRACT_FILES[name];
  const file = path.join(ARTIFACTS, rel, `${name}.json`);
  if (!fs.existsSync(file)) {
    throw new Error(`Missing artifact for ${name} at ${file}. Run: npm run compile -w @hesoyam/contracts`);
  }
  return JSON.parse(fs.readFileSync(file, "utf8")).abi;
}

function writeAbis() {
  const parts = [
    "// Generated by packages/sdk/scripts/generate.js. Do not edit.",
    "// Regenerate with: npm run generate -w @hesoyam/sdk",
    "",
  ];

  for (const name of Object.keys(CONTRACT_FILES)) {
    const abi = readAbi(name);
    parts.push(`export const ${lowerFirst(name)}Abi = ${JSON.stringify(abi, null, 2)} as const;`);
    parts.push("");
  }

  fs.writeFileSync(path.join(OUT, "abis.ts"), parts.join("\n"));
  return Object.keys(CONTRACT_FILES).length;
}

function writeAddresses() {
  const records = {};
  if (fs.existsSync(DEPLOYMENTS)) {
    for (const file of fs.readdirSync(DEPLOYMENTS)) {
      if (!file.endsWith(".json")) continue;
      const record = JSON.parse(fs.readFileSync(path.join(DEPLOYMENTS, file), "utf8"));
      records[record.chainId] = record;
    }
  }

  const parts = [
    "// Generated by packages/sdk/scripts/generate.js. Do not edit.",
    "",
    "export type ContractName =",
    ...Object.keys(DEPLOYMENT_KEYS).map((n) => `  | "${n}"`),
    ";",
    "",
    "export type Deployment = {",
    "  network: string;",
    "  chainId: number;",
    "  startBlock: number;",
    "  deployedAt: string;",
    "  addresses: Partial<Record<ContractName, `0x${string}`>>;",
    "};",
    "",
    "export const DEPLOYMENT_KEYS: Record<ContractName, string> = " +
      JSON.stringify(DEPLOYMENT_KEYS, null, 2) +
      " as const;",
    "",
  ];

  const byChain = {};
  for (const [chainId, record] of Object.entries(records)) {
    const addresses = {};
    for (const [name, key] of Object.entries(DEPLOYMENT_KEYS)) {
      if (record.addresses[key]) addresses[name] = record.addresses[key];
    }
    byChain[chainId] = {
      network: record.network,
      chainId: record.chainId,
      startBlock: record.startBlock,
      deployedAt: record.deployedAt,
      addresses,
    };
  }

  parts.push(
    "export const DEPLOYMENTS: Record<number, Deployment> = " + JSON.stringify(byChain, null, 2) + ";",
    ""
  );

  fs.writeFileSync(path.join(OUT, "addresses.ts"), parts.join("\n"));
  return Object.keys(byChain);
}

function main() {
  fs.mkdirSync(OUT, { recursive: true });
  const abiCount = writeAbis();
  const chains = writeAddresses();
  console.log(`Generated ${abiCount} ABIs.`);
  console.log(
    chains.length
      ? `Generated addresses for chain ids: ${chains.join(", ")}.`
      : "No deployment records found. Deploy first, then regenerate."
  );
}

main();
