/**
 * Creates a fresh deployer wallet.
 *
 * The private key is written to .env and is never printed. A key echoed to a
 * terminal ends up in scrollback, in shell history, and in any transcript of the
 * session that produced it, which is three more places than it should ever exist.
 * Open the file yourself if you need to copy it.
 *
 * Refuses to overwrite an existing key, because silently replacing a funded
 * deployer is how people lose contracts they already paid to deploy.
 *
 * Usage: npm run wallet:new
 */
const fs = require("fs");
const path = require("path");
const { Wallet } = require("ethers");

const ROOT = path.join(__dirname, "..");
const ENV = path.join(ROOT, ".env");

function readEnv() {
  if (!fs.existsSync(ENV)) return {};
  const out = {};
  for (const line of fs.readFileSync(ENV, "utf8").split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)$/);
    if (m) out[m[1]] = m[2];
  }
  return out;
}

function main() {
  const existing = readEnv();

  if (existing.DEPLOYER_KEY && existing.DEPLOYER_KEY.length > 10) {
    const w = new Wallet(existing.DEPLOYER_KEY);
    console.log("\nA deployer key already exists in .env.");
    console.log(`  address  ${w.address}`);
    console.log("\nRefusing to overwrite it. If you genuinely want a new one, move");
    console.log("the old .env aside first, and make sure nothing is deployed from it.\n");
    return;
  }

  // ethers uses the platform CSPRNG for this. Do not replace it with anything
  // seeded from time, a mnemonic you typed, or Math.random.
  const wallet = Wallet.createRandom();

  const lines = [
    "# Generated by scripts/new-wallet.cjs. Never commit this file.",
    "# This is a hot deployer key. Fund it with only what a deploy costs.",
    `DEPLOYER_KEY=${wallet.privateKey}`,
    "",
    "# Fill these in before deploying anywhere real.",
    `ARBITRUM_SEPOLIA_RPC=${existing.ARBITRUM_SEPOLIA_RPC || ""}`,
    `TARGET_RPC=${existing.TARGET_RPC || ""}`,
    `TARGET_CHAIN_ID=${existing.TARGET_CHAIN_ID || ""}`,
    "",
  ];
  fs.writeFileSync(ENV, lines.join("\n"), { mode: 0o600 });

  // Also stash the mnemonic separately so a backup is possible without opening
  // the file the tooling reads.
  const backup = path.join(ROOT, ".env.wallet-backup");
  fs.writeFileSync(
    backup,
    [
      "# BACKUP ONLY. Never commit. Store this somewhere offline, then delete this file.",
      `address:  ${wallet.address}`,
      `mnemonic: ${wallet.mnemonic ? wallet.mnemonic.phrase : "(none)"}`,
      "",
    ].join("\n"),
    { mode: 0o600 }
  );

  console.log("\nNew deployer wallet created.\n");
  console.log(`  address   ${wallet.address}`);
  console.log("  key       written to .env, not shown here on purpose");
  console.log("  mnemonic  written to .env.wallet-backup, not shown here either");
  console.log("\nBoth files are gitignored. Back up the mnemonic offline, then delete");
  console.log(".env.wallet-backup.\n");
  console.log("Fund the address above, then check the balance with:");
  console.log("  npm run wallet:check -- --network arbitrumSepolia\n");
}

main();
